#!/usr/bin/php
<?php
/*
        Indiestor program

	Written by Erik Poupaert, erik@sankuru.biz
        Commissioned at peopleperhour.com 
        By Alex Gardiner, alex.gardiner@canterbury.ac.uk
*/

require_once('lib/commandline/args/CommandLineArgs.php');

$commandLineArgs=new CommandLineArgs($argv);
echo ProgramConfig::toString();

