#!/usr/bin/php
<?php
/*
        Indiestor program

	Written by Erik Poupaert, erik@sankuru.biz
        Commissioned at peopleperhour.com 
        By Alex Gardiner, alex.gardiner@canterbury.ac.uk
*/

require_once('lib/common/require_once_folder.php');
require_once('lib/admin/args/ProgramActions.php');
require_once('lib/admin/args/ProgramOptions.php');
require_once('lib/admin/ArgEngine.php');
require_once('lib/admin/ActionEngine.php');
require_once('lib/common/Shell/ShellCommand.php');
require_once('lib/common/DefinitionFile.php');
require_once('lib/common/NoticeDefinitions.php');

//check that the user is root
$processUser = posix_getpwuid(posix_geteuid());
$processUserName=$processUser['name'];
if($processUserName!='root')
{
	NoticeDefinitions::instance()->error('EXEC_ROOT_ONLY');
}

//check that shell_exec is allowed
if(false !== strpos(ini_get('disable_functions'), 'shell_exec'))
{
	NoticeDefinitions::instance()->error('SHELL_EXEC_DISABLED');
}

//check that the quota commands are installed
$quotaCommands=array('quota','quotaon','quotacheck','quotaoff','setquota');
$quotaInstalled=true; //assume the quota package has properly been installed
foreach($quotaCommands as $quotaCommand)
{
	$location=trim(shell_exec("which $quotaCommand"));
	if(strlen($location)==0) 
	{
		NoticeDefinitions::instance()->warning('QUOTA_COMMAND_NOT_INSTALLED',array('command'=>$quotaCommand));
		$quotaInstalled=false;
	}
}
if(!$quotaInstalled) NoticeDefinitions::instance()->error('QUOTA_PACKAGE_NOT_INSTALLED');

$argEngine=new ArgEngine($argv);
$argEngine->process();

ProgramOptions::extractFromProgramActions();

ActionEngine::execute();

