#!/usr/bin/php
<?php
echo "executing indiestor-inotify...\n";

$outputFileName=dirname(__FILE__).'/incron.log';
$outputFile=fopen($outputFileName,'a');

ini_set('display_errors','On');

$date=date(DATE_RFC822);
$watchType=$argv[1];
$folderWatched=$argv[2];
$fsObject=$argv[3];
$events=$argv[4];

require_once('lib/inotify/InotifyEventHandler.php');

$inMovePendingPath=dirname(__FILE__).'/in_move_pending';
if(!is_dir($inMovePendingPath)) mkdir($inMovePendingPath);
$inotifyEventHandler=new InotifyEventHandler($inMovePendingPath);

//process number
$pid=getmypid();

fputs($outputFile,"pid=$pid folder='$folderWatched' type='$watchType' object='$fsObject' events='$events'\n");

try
{
	$decision=$inotifyEventHandler->decision($watchType,$folderWatched,$fsObject,$events);
}
catch(Exception $e)
{
	$decision='ERROR:'.$e->getMessage();
}

if($decision instanceof RenameOperation)
{
	$from=$decision->from;
	$to=$decision->to;
	$decision="RENAME '$from' TO '$to'";
}

fputs($outputFile,"====>pid=$pid decision=$decision\n");
fclose($outputFile);

