#!/usr/bin/php
<?php
/*
        Indiestor program

	Written by Erik Poupaert, erik@sankuru.biz
        Commissioned at peopleperhour.com 
        By Alex Gardiner, alex.gardiner@canterbury.ac.uk
*/

require_once('lib/admin/require_once_folder.php');
require_once('lib/admin/args/ProgramActions.php');
require_once('lib/admin/args/ProgramOptions.php');
require_once('lib/admin/ArgEngine.php');
require_once('lib/admin/ActionEngine.php');
require_once('lib/admin/ShellCommand.php');
require_once('lib/admin/DefinitionFile.php');
require_once('lib/admin/NoticeDefinitions.php');
require_once('lib/inotify/reshare.php');

//check that the user is root
$processUser = posix_getpwuid(posix_geteuid());
$processUserName=$processUser['name'];
if($processUserName!='root')
{
	NoticeDefinitions::instance()->error('EXEC_ROOT_ONLY');
}

//check that shell_exec is allowed
if(false !== strpos(ini_get('disable_functions'), 'shell_exec'))
{
	NoticeDefinitions::instance()->error('SYS_ERR_SHELL_EXEC_DISABLED');
}

$argEngine=new ArgEngine($argv);
$argEngine->process();

ProgramOptions::extractFromProgramActions();

ActionEngine::execute();

